import Joi from 'joi';

export const joiSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production', 'test'),
  HOST_URL: Joi.string().uri(),
  DATABASE_URL: Joi.string().uri().required(),
  S3_REGION: Joi.string().required(),
  S3_ACCESS_KEY_ID: Joi.string().required(),
  S3_SECRET_ACCESS_KEY: Joi.string().required(),
  S3_BUCKET: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  NODEMAILER_USER: Joi.string().email().required(),
  NODEMAILER_PASS: Joi.string().required(),
  NODEMAILER_SENDER_EMAIL: Joi.string().email().required(),
  STRIPE_API_KEY: Joi.string().required(),
  STRIPE_WEBHOOK_SECRET: Joi.string().optional(),
  STRIPE_CHECKOUT_SUCCESS_URL: Joi.string().uri().required(),
  STRIPE_CHECKOUT_CANCEL_URL: Joi.string().uri().required(),
  PAYPAL_CLIENT_ID: Joi.string().required(),
  PAYPAL_CLIENT_SECRET: Joi.string().required(),
  PAYPAL_MODE: Joi.string().valid('sandbox', 'live').optional(),
  PAYPAL_WEBHOOK_ID: Joi.string().optional(),
  REDIS_HOST: Joi.string().optional(),
  REDIS_PORT: Joi.number().optional(),
  REDIS_USERNAME: Joi.string().optional(),
  REDIS_PASSWORD: Joi.string().optional(),
  REDIS_DB: Joi.number().optional(),
  REDIS_TLS: Joi.string().valid('true', 'false').optional(),
});
